#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
#
# :P centos http://superuser.com/questions/738829/attempting-to-install-tmux-on-centos-6-4-or-centos-6-5-fails-with-error-evbuff
export LD_LIBRARY_PATH=/usr/local/lib

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias c="clear"

# vim
set -o vi
export EDITOR=vim
export VISUAL=vim
alias v='vim'
alias vd='vimdiff'
alias vs="vim --servername $(tmux display-message -p '#S')"

# git
alias g="git"
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gca="git commit -a"
alias gch="git checkout"
alias gd="git diff"
alias gb="git branch"
alias gl="git log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
# Checkout out the git branch with the same name as the current tmux session
alias gcht="git checkout `tmux display-message -p '#S'`"

# tmux
alias tmux="tmux -2"
alias tl="tmux list-sessions"
alias tn="tmux new-session -s"
alias tx="tmux attach-session -t"
alias tw="tmux_attach"
alias ts="tmux attach-session \; choose-session"
# Mirror the current git branch name as a session
# FIXME chop off the branch "version"
alias tm="BRANCH=`git rev-parse --abbrev-ref HEAD | cut -d/ -f2 | sed 's/_[0-9]\+$//g'`; ; tmux attach-session -t $BRANCH || tmux new-session -s $BRANCH"

function tmux_attach() { 
    echo tmux new-session -s "$@"-w "$@" 
    tmux new-session -s "$@"-w -t "$@" 
}

# History stuff
bindkey "^[[A" history-search-backward
bindkey "^[[B" history-search-forward

# Restore reverse search goodness
bindkey "^R" history-incremental-search-backward

# Source local stuff
if [ -f $HOME/.zshrc.local ]; then
    source $HOME/.zshrc.local
fi

# Playing with gpg
# FIXME: ideally find a quick way to skip this if already loaded. environment variable/etc.
function start_gpgagent() {
gpg-agent --daemon --enable-ssh-support \
    --write-env-file "${HOME}/.gpg-agent-info" >/dev/null

if [ -f "${HOME}/.gpg-agent-info" ]; then
    . "${HOME}/.gpg-agent-info"
    export GPG_AGENT_INFO
    export SSH_AUTH_SOCK
fi
}
GPG_TTY=$(tty)
export GPG_TTY

# If I am root expand my worldview
if [ "$(whoami)" = "root" ]; then 
    PATH=$PATH:/usr/local/sbin:/sbin:/usr/sbin
fi

fcat() { for f in "$@"; do echo "$@"; echo -e "\n==> $f <=="; cat "$f"; done; }

# WIP: log phpunit results and filter to failed results only if tests failed,
# otherwise run all
# This will need to take current test suite into account
# FIXME: send failed tests to vim somehow. Perhaps this should run via :Test.
# Would be cool to syntax highlight failed tests
# FIXME: dont hardcode home
# FIXME: could this step up though directories until it finds phpunit.xml
# making tests work from any directory
# FIXME: support multiple test results (hash directory)
t() {
    FILTER=""
    if [ -f '/home/bjohnson/.phpunit/log' ]; then

        if grep '^not ok' '/home/bjohnson/.phpunit/log' >/dev/null
        then
            FILTER=" --filter '$(echo $(grep '^not ok' '/home/bjohnson/.phpunit/log' | cut -d ' ' -f6 | cut -d \\ -f2 | xargs) | sed 's/ /|/g')'"
        fi
    fi

    COMMAND="/usr/bin/php -d 'html_errors=0' $HOME/bin/phpunit --log-tap ~/.phpunit/log $FILTER"
    eval $COMMAND
}

prompt robbyrussellhacked
        
# suffix aliases for file open goodness
alias -s php=vim
alias -s xml=vim
alias -s html=vim

alias composer="php $HOME/tools/composer.phar"

export PATH=$HOME/bin:$PATH
export PATH=$PATH:/usr/local/bin:/bin:/usr/bin:$HOME/.composer/vendor/bin

# List any open tmux sessions
if [ `whoami` != 'root' ]; then
    tmux list-sessions
fi

alias ack="ack-grep"
alias boris="~/tools/boris/bin/boris";
alias o="xdg-open"
alias s="source ~/.zshrc"

set horizontal-scroll-mode on
alias emacs="emacs-snapshot -nw"

# docker
alias docker="docker"
alias d="docker"
alias di="docker images"
alias dp="docker ps"
alias da='lxc-attach -n $(docker ps -notrunc | sed 1d | cut -d " " -f1)'
